#!/bin/bash
#BSUB -J manhattan[1-2]
#BSUB -q long
#BSUB -n 4
#BSUB -M 64
#BSUB -R rusage[mem=64]
#BSUB -W 25:00
#BSUB -o /rsrch8/home/biostatistics/swang25/other_summary_statistics/Fig1/errDir/manhattan_%I.out
#BSUB -e /rsrch8/home/biostatistics/swang25/other_summary_statistics/Fig1/errDir/manhattan_%I.err
#BSUB -cwd /rsrch8/home/biostatistics/swang25/other_summary_statistics

module load R/4.4.1
export R_LIBS_USER="/home/swang25/R/ubuntu/4.4.1"
module load singularity

# Execute the R script
/risapps/rhel8/R/4.4.1/lib64/R/bin/Rscript /rsrch8/home/biostatistics/swang25/other_summary_statistics/Fig1/plot_manhattan.R $LSB_JOBINDEX 1